### PR TITLE
Updated to version of ICI with VCS shallow cloning

### PR DESCRIPTION
**Pull request by marip8**
Updates CI to use custom version of ICI with that clones shallow with VCS in addition to supporting ROS-independent builds

### CODE REVIEW

**Review by Levi-Armstrong — APPROVED** [review]
Pending CI passes

**Comment by Levi-Armstrong** [comment]
@marip8 you good with merging this?

**Comment by marip8** [comment]
LGTM. I can't merge because the "required" checks won't run and I don't have permissions to override

**Comment by Levi-Armstrong** [comment]
@marip8 See if you can merge it now.

**Pull request merged**
