### PR TITLE
Fix use of compound mesh in FCL

### LINKED ISSUE #1053: CompoundMesh does not work with FCL
[CompoundMesh ](https://github.com/tesseract-robotics/tesseract/pull/1046) does not work with the FCL collision checker. I suppose it is because for Bullet, one CompoundMesh is added as one compound object, whereas for FCL, one CompoundMesh is added a multiple objects.

I've taken a look, it seems FCL does not support compound objects, apart from [BHVModel](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/geometry/bvh/BVH_model.h), which only supports meshes or pointclouds as submodels.

And for reference, neither does HPP-FCL: [#340](https://github.com/humanoid-path-planner/hpp-fcl/issues/340), [#448](https://github.com/humanoid-path-planner/hpp-fcl/issues/448).

### PR DESCRIPTION
**Pull request by Levi-Armstrong**
Fix #1053 

@rjoomen After looking through the code I went a slight different route to solve another issue with get the correct shape index. Do you mind testing this?

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@rjoomen Hey, I did not realize you had pushed changes and I force pushed after I noticed my local clang tidy build failed. What changes did you make?

**Comment by rjoomen** [comment]
No changes, I just rebased on master using Github.

**Comment by rjoomen** [comment]
I'll look into this tomorrow.

**Comment by rjoomen** [comment]
Seems like a better solution, and it works, thanks. I added a small simplification.

**Pull request merged**
