### PR TITLE
Add CI for Ubuntu Noble

### PR DESCRIPTION
**Pull request by marip8**

### CODE REVIEW

**Comment by marip8** [comment]
I don't really have time at the moment to see this PR through, but we ought to start supporting builds on `noble` since we are merging other PRs that address build compatibility on that platform

**Comment by rjoomen** [comment]
That's strange, with colcon-action@v7 both Jammy and Noble say:
```
E: Unable to locate package python3-vcstool
E: Unable to locate package python3-colcon-common-extensions
E: Unable to locate package python3-rosdep
```
But I've checked, on my Jammy and Noble installations these packages are available.

**Comment by rjoomen** [comment]
- CI for Ubuntu/noble works. The build fails, as expected, on Noble-related issues, but not on the CI setup itself (see e.g. [here](https://github.com/tesseract-robotics/tesseract_qt/issues/111)).
- CI for Docker/noble needs [fixes similar to colcon-action](https://github.com/tesseract-robotics/colcon-action/pull/11), could you look into that, @marip8?

Once we have this PR merged I'll start updating the CIs of the other projects as well.

**Comment by rjoomen** [comment]
This can be merged now.

**Review by Levi-Armstrong — APPROVED** [review]

**Pull request merged**
