### PR TITLE
Add more clone benchmarks

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@johnwason Do you know why everything for windows, conda and mac os is failing now? Everything passed in the latest [MR](https://github.com/tesseract-robotics/tesseract/pull/990/checks) that was merged.

**Comment by johnwason** [comment]
I am not seeing errors locally. I will check on github actions and see if I can capture more data.

**Comment by johnwason** [comment]
See https://github.com/microsoft/vcpkg/discussions/38140

**Comment by johnwason** [comment]
Apparently this is a problem with CMake 3.29.1

https://github.com/microsoft/vcpkg/issues/37968

**Comment by johnwason** [comment]
I am testing adding this step before vcpkg and build steps:

```
   - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.28.x'
```

**Comment by johnwason** [comment]
Changing the cmake version worked. https://github.com/johnwason/tesseract/actions/runs/8656859533/job/23738056581

The error is from my artifact capturing, the build did work.

**Comment by Levi-Armstrong** [comment]
@johnwason Can this also be used to fix the conda builds?

**Comment by Levi-Armstrong** [comment]
It looks like changing the cmake version fixed the windows builds, but still need to figure out mac and conda build issue.

**Pull request merged**
