### PR TITLE
Documentation/Code Coverage CI Update

### PR DESCRIPTION
**Pull request by marip8**
I think this should fully address #867. I think we should see a code coverage post to this PR if it works correctly

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
It looks like it found the reports but failed to upload them.

**Comment by Levi-Armstrong** [comment]
I just restarted codecov build to see if anything changes with the upload.

**Comment by marip8** [comment]
I encountered the same issues while testing locally. Do we just need to regenerate the code-cov token? Also should that be a repository secret? The [code-cov quick start guide](https://docs.codecov.com/docs/quick-start#step-4-upload-coverage-reports-to-codecov) seems to suggest that

**Comment by Levi-Armstrong** [comment]
Yea, probably. Do you have access?

**Comment by Levi-Armstrong** [comment]
@marip8 It looks like it does not like it cannot find the token variable.

**Comment by Levi-Armstrong** [comment]
@marip8 You have any ideas how to get this to work?

**Comment by Levi-Armstrong** [comment]
@marip8 The issues is that codecov needs to be ran from within the tesseract repos directory because that is where the codecov.yaml file is located.

before:
```
AFTER_SCRIPT: catkin build -w $target_ws --no-deps tesseract_collision tesseract_common tesseract_environment tesseract_geometry tesseract_kinematics tesseract_srdf tesseract_state_solver tesseract_scene_graph tesseract_urdf --make-args ccov-all && bash <(curl -s https://codecov.io/bash) -t c4af0da7-9fc3-4d3c-bb2e-6b2523ddd382 -s $target_ws/build -f *all-merged.info
```

**Comment by Levi-Armstrong** [comment]
I think I am down to the remaining issue. The current upload request is missing things like branch, commit, etc.

Original upload request
```
2023-03-09T05:46:50.0552648Z https://codecov.io/upload/v4?package=bash-1.0.6&token=<hidden>&package=bash-1.0.6&token=c4af0da7-9fc3-4d3c-bb2e-6b2523ddd382&branch=master&commit=4f04a9191aea239f38fbef8fce9ce457d46b0d15&build=&build_url=&name=&tag=&slug=tesseract-robotics%2Ftesseract&service=&flags=&pr=&job=&cmd_args=t,s,f
2023-03-09T05:46:50.0553340Z [0;90m->[0m  Uploading to
```

Current upload request
```
2023-04-08T20:30:00.5487018Z https://codecov.io/upload/v4?package=bash-1.0.6&token=<hidden>&package=bash-1.0.6&token=758610a6-d851-4185-a01a-5b9465889b62&branch=&commit=&build=&build_url=&name=&tag=&slug=&service=&flags=&pr=&job=&cmd_args=t,s,f
2023-04-08T20:30:00.5487605Z [0;31mInvalid request parameters
```

**Comment by Levi-Armstrong** [comment]
@marip8 I worked through all of the issues and it now uploading. Take a look at the after script, but I was unable to figure out how to leverage the secrets token, but I will merge this and we can figure that out later.

**Pull request merged**
