### PR TITLE
A few fixes that were needed for Windows

### PR DESCRIPTION
**Pull request by jdlangs**
The three commits here:

- Bullet extras are not easily obtained on Windows so this makes building the HACD convex decomposition library optional
- Paths to bullet are specified as `${BULLET_ROOT_DIR}/${BULLET_INCLUDE_DIRS}`, e.g., but the include dirs already contains absolute paths. ~Probably this wasn't noticed on Ubuntu since it would already be looking in the system install dirs.~ This is a result of packaging for vcpkg and is different from the version packaged for Ubuntu.
- Had a compile error since a header used but didn't include `std::string`

### CODE REVIEW

**Comment by jdlangs** [comment]
I'll work through what's going wrong with the build later tonight.

**Comment by jdlangs** [comment]
Ok, I didn't realize the Ubuntu installed version *does* use a root dir prefix and relative paths for the other variables. After looking into, it seems the vcpkg version of Bullet [rewrites](https://github.com/microsoft/vcpkg/blob/master/ports/bullet3/cmake-fix.patch#L1-L36) the CMake config file, which I assume is where the absolute paths are coming from. I can redo the commit to take into account both situations, unless there's another suggestion.

**Comment by Levi-Armstrong** [comment]
> Ok, I didn't realize the Ubuntu installed version _does_ use a root dir prefix and relative paths for the other variables. After looking into, it seems the vcpkg version of Bullet [rewrites](https://github.com/microsoft/vcpkg/blob/master/ports/bullet3/cmake-fix.patch#L1-L36) the CMake config file, which I assume is where the absolute paths are coming from. I can redo the commit to take into account both situations, unless there's another suggestion.

In the case where they are using absloute path is the BULLET_ROOT_DIR empty? If so you could just do a check at the top which defines a local variable for the path based on if it is empty or not.

**Comment by jdlangs** [comment]
It's not empty but I can still use that strategy. I see CMake has an `IS_ABSOLUTE` check on paths that can be used first.

**Comment by Levi-Armstrong** [comment]
It looks good to merge once the cmake format is resolved.

**Comment by jdlangs** [comment]
I don't see anything in the log that shows what went wrong.

**Comment by Levi-Armstrong** [comment]
> I don't see anything in the log that shows what went wrong.

I would just run `./.run-cmake-formate` script and it will take care of the formatting issue.

**Comment by jdlangs** [comment]
> I would just run `./.run-cmake-formate` script and it will take care of the formatting issue.

Will do, but that probably shouldn't be blocking contributions if people can't see what's wrong.

**Comment by Levi-Armstrong** [comment]
> > I would just run `./.run-cmake-formate` script and it will take care of the formatting issue.
> 
> Will do, but that probably shouldn't be blocking contributions if people can't see what's wrong.

I have updated the [CI](https://github.com/tesseract-robotics/tesseract/pull/709) to output and error message stating to run the script and also output the diff if you want to manually make the change.

**Comment by jdlangs** [comment]
Awesome, thanks for adding that!

I've adjusted the CMake formatting so we should be good to go.

**Pull request merged**
