### PR TITLE
Updated Dockerfile to support 24.04

### PR DESCRIPTION
**Pull request by marip8**
Adds changes similar to #1006 to support Docker image build on 24.04

### CODE REVIEW

**Comment by marip8** [comment]
The docker build for noble works, it just fails to build per the comment [here](https://github.com/tesseract-robotics/tesseract/pull/1006#issuecomment-2178715775)

**Comment by rjoomen** [comment]
Yep, ready to be merged.

**Comment by rjoomen** [comment]
Ready to be merged, unless you want to follow up on @johnwason 's comment https://github.com/tesseract-robotics/colcon-action/issues/12 here as well.

**Comment by Levi-Armstrong** [comment]
Lets try the --user option instead of having to the ros PPA.

**Comment by rjoomen** [comment]
This can now be merged (because https://github.com/tesseract-robotics/colcon-action/pull/14).

**Review by Levi-Armstrong — APPROVED** [review]

**Pull request merged**
